# Generated by Django 3.2.9 on 2022-11-02 14:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('count', models.IntegerField(default=1)),
                ('completed_count', models.IntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='modules.module')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
