# Generated by Django 3.2.9 on 2022-10-24 14:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('uuid', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('category', models.CharField(choices=[('condensers', 'Condensers'), ('diodes', 'Diodes'), ('connectors', 'Connectors'), ('inductors', 'Inductors'), ('transistors', 'Transistors'), ('resistors', 'Resistors'), ('trimmers', 'Trimmers'), ('integrated-resonators', 'Integrated-resonators'), ('misc', 'Misc')], max_length=256)),
                ('title', models.CharField(max_length=512, null=True)),
                ('description', models.CharField(max_length=512, null=True)),
                ('tme_type', models.CharField(max_length=512, null=True)),
                ('farnell_code', models.CharField(max_length=512, null=True)),
                ('comp_value', models.CharField(max_length=512, null=True)),
                ('comp_class', models.CharField(max_length=512, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('min_price', models.FloatField(default=0)),
                ('current_price', models.FloatField(default=0)),
            ],
            options={
                'ordering': ('uuid',),
            },
        ),
        migrations.CreateModel(
            name='PartOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=256)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
