# Generated by Django 3.2.9 on 2022-10-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='stock',
            field=models.BigIntegerField(default=0),
        ),
    ]
