# Generated by Django 3.2.9 on 2022-10-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('name',)},
        ),
    ]
