# Generated by Django 3.2.9 on 2022-10-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_device_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devicemodule',
            unique_together={('module', 'device')},
        ),
    ]
