# Generated by Django 3.2.9 on 2022-11-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
    ]
