# Generated by Django 3.2.9 on 2022-10-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
        ('orders', '0002_auto_20221024_1602'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderpart',
            unique_together={('order', 'part')},
        ),
    ]
