# Generated by Django 3.2.9 on 2022-10-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderpart_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpart',
            name='count',
            field=models.BigIntegerField(default=1),
        ),
    ]
