# Generated by Django 3.2.9 on 2022-10-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderpart_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpart',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
